name: Scrape Rightmove

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py


      - name: Read results.json into env variable
        id: readjson
        run: |
          {
            echo "RESULTS<<EOF"
            cat results.json
            echo "EOF"
          } >> $GITHUB_ENV



      - name: Send email with results in body
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: 1337.david.smith.1337
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Rightmove Results - ${{ github.run_number }}"
          to: dragoneternaluk@gmail.com
          from: GitHub Actions <your-email@gmail.com>
          content_type: text/plain
          body: |
            Hello,

            Here are the latest Rightmove results:

            ${{ env.RESULTS }}

            — GitHub Actions
