name: Scrape Rightmove

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: |
        python scraper.py
        if [ ! -s results.json ]; then
          echo "No new results. Skipping commit and email."
          exit 0
        fi

    - name: Send email with HTML formatting
      env:
        EMAIL_USER: 1337.david.smith.1337
        EMAIL_PASS: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: dragoneternaluk@gmail.com
      run: |
        python - <<EOF
        import smtplib
        import json
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText

        with open('results.json', encoding='utf-8') as f:
            data = json.load(f)

        count = len(data)
        plain_lines = [f"Found {count} new properties:\n"]
        html_lines = [f"<h2>Found {count} new properties:</h2><ul>"]

        for pid, prop in data.items():
            address = prop.get("address", "")
            price = prop.get("price", "")
            ptype = prop.get("type", "")
            beds = prop.get("beds", "")
            baths = prop.get("baths", "")
            images = prop.get("images", "")
            desc = prop.get("description", "")

            plain_lines.append(f"Address: {address}")
            plain_lines.append(f"Price: {price}")
            plain_lines.append(f"Type: {ptype}")
            plain_lines.append(f"Beds: {beds}")
            plain_lines.append(f"Baths: {baths}")
            plain_lines.append(f"Images: {images}")
            plain_lines.append(f"Description: {desc}")
            plain_lines.append("------------------------------")

            html_lines.append(f"""
<li>
  <strong>Address:</strong> {address}<br>
  <strong>Price:</strong> {price}<br>
  <strong>Type:</strong> {ptype}<br>
  <strong>Beds:</strong> {beds} | <strong>Baths:</strong> {baths} | <strong>Images:</strong> {images}<br>
  <strong>Description:</strong> {desc}
  <hr>
</li>
""")

        html_lines.append("</ul>")

        msg = MIMEMultipart("alternative")
        msg["Subject"] = "Rightmove Results - GitHub Actions"
        msg["From"] = "${EMAIL_USER}"
        msg["To"] = "${EMAIL_TO}"

        part1 = MIMEText("\n".join(plain_lines), "plain", "utf-8")
        part2 = MIMEText("".join(html_lines), "html", "utf-8")

        msg.attach(part1)
        msg.attach(part2)

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login("${EMAIL_USER}", "${EMAIL_PASS}")
            server.sendmail("${EMAIL_USER}", "${EMAIL_TO}", msg.as_string())
EOF

    - name: Commit updated seen.json and results.json if new listings found
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add seen.json results.json || true
        git diff --cached --quiet || (git commit -m "Update seen and results" && git push)
